const defaultState = {
  loading: false,
  notice: '',
  billIndex: 0,
  confirm: '',
  dialog: false,
  report: false,
  reg: false,
  update: false,
  name: '',
  email: '',
  phone: '',
  dien: '',
  nuoc: '',
  nha: '',
  onlyDeposit: false,
  deposit: '',
  thukhac: '',
  tienthukhac: '',
  chi: '',
  tienchi: '',
  openThuchi: false,
}

export default defaultState
