const state = {
  room: '',
  loading: false,
  notice: '',
  datas: [],
  roomIndex: 0,
  billIndex: 0,
  confirm: '',
  showAll: true,
  sthChanged: true,
  month: 1,
  months: [],
  year: 2018,
  years: [],
  dialog: false,
  token: '',
  report: false,
  reg: false,
  update: false,
  name: '',
  email: '',
  phone: '',
  dien: '',
  nuoc: '',
  nha: '',
  onlyDeposit: false,
  deposit: '',
  thukhac: '',
  tienthukhac: '',
  chi: '',
  tienchi: '',
  openThuchi: false,
  thuchi: [],
  thuchiState: [],
  thuchiClone: [],
  ver: '20190410.1824',
  sv: '',
}

export default state
